// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerpustakaanMVC.Data;

#nullable disable

namespace PerpustakaanMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250820031914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PerpustakaanMVC.Models.Anggota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Anggota");
                });

            modelBuilder.Entity("PerpustakaanMVC.Models.Buku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Penerbit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Penulis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("StatusDipinjam")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Buku");
                });

            modelBuilder.Entity("PerpustakaanMVC.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnggotaId")
                        .HasColumnType("int");

                    b.Property<int>("BukuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TanggalKembali")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AnggotaId");

                    b.HasIndex("BukuId");

                    b.ToTable("Peminjaman");
                });

            modelBuilder.Entity("PerpustakaanMVC.Models.Peminjaman", b =>
                {
                    b.HasOne("PerpustakaanMVC.Models.Anggota", "Anggota")
                        .WithMany()
                        .HasForeignKey("AnggotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerpustakaanMVC.Models.Buku", "Buku")
                        .WithMany()
                        .HasForeignKey("BukuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anggota");

                    b.Navigation("Buku");
                });
#pragma warning restore 612, 618
        }
    }
}
